
import { NextResponse } from 'next/server';
import Razorpay from 'razorpay';
import { v4 as uuidv4 } from 'uuid';

export async function POST(request: Request) {
    const keyId = process.env.RAZORPAY_KEY_ID;
    const keySecret = process.env.RAZORPAY_KEY_SECRET;

    if (!keyId || !keySecret) {
        console.error("Razorpay API keys are not set in environment variables.");
        return new NextResponse(
            JSON.stringify({ error: "Server configuration error: Razorpay keys are missing." }),
            { status: 500, headers: { 'Content-Type': 'application/json' } }
        );
    }
    
    const razorpay = new Razorpay({
        key_id: keyId,
        key_secret: keySecret,
    });

    try {
        const { amount, customerName, customerContact, customerEmail, orderId, productName } = await request.json();

        if (!amount || !customerName || !customerContact || !orderId) {
            return new NextResponse(
                JSON.stringify({ error: "Missing required fields: amount, customerName, customerContact, orderId" }),
                { status: 400, headers: { 'Content-Type': 'application/json' } }
            );
        }
        
        const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://snazzpay.apphosting.page';
        
        // Construct the URL to the app's own Secure COD page
        const secureCodUrl = new URL(`${appUrl}/secure-cod`);
        secureCodUrl.searchParams.set('amount', amount);
        secureCodUrl.searchParams.set('name', productName);
        secureCodUrl.searchParams.set('order_id', orderId);
        
        const shortUrlResponse = await razorpay.paymentLink.create({
            amount: 100, // Minimum amount for a payment link is Rs. 1
            currency: "INR",
            accept_partial: false,
            description: `Click the link to complete Secure COD authorization for order ${orderId}.`,
            customer: {
                name: customerName,
                contact: customerContact,
                email: customerEmail || undefined,
            },
            notes: {
                "Complete Secure COD for Order": orderId,
                "Link": secureCodUrl.toString()
            },
            reminder_enable: false,
            expire_by: Math.floor(Date.now() / 1000) + (24 * 60 * 60), // Expire in 24 hours
            callback_url: secureCodUrl.toString(), // Redirect after dummy payment
            callback_method: "get" as const
        });
        
        // Use the short URL generated by Razorpay to send via notifications
        const notificationMessageText = `Hello ${customerName}, please complete the Secure COD authorization for your order '${productName}'. Click here: ${shortUrlResponse.short_url}`;

        const paymentLinkOptions = {
            amount: Math.round(parseFloat(amount) * 100), // Amount in paise
            currency: "INR",
            accept_partial: false,
            description: notificationMessageText,
            customer: {
                name: customerName,
                contact: customerContact,
                email: customerEmail || undefined,
            },
            notify: {
                sms: true,
                email: !!customerEmail,
                whatsapp: true
            },
            reminder_enable: true,
            notes: {
                order_id: orderId,
                product_name: productName,
                secure_cod_url: secureCodUrl.toString()
            },
            callback_url: `${appUrl}/orders/${orderId}`,
            callback_method: "get" as const
        };
        
        // We are creating a payment link but using its notification feature to send our own app link
        await razorpay.paymentLink.create(paymentLinkOptions);
        
        console.log("Successfully triggered Razorpay Payment Link notifications to send Secure COD link.");

        let sentTo = ['SMS', 'WhatsApp'];
        if (customerEmail) {
            sentTo.push('Email');
        }
        const notificationMessage = `Secure COD link sent to ${customerContact} via ${sentTo.join(', ')}.`;

        return NextResponse.json({
            success: true,
            message: notificationMessage
        });

    } catch (error: any) {
        console.error("--- Razorpay Payment Link API Error ---");
        if (error.error) {
             console.error(JSON.stringify(error.error, null, 2));
        } else {
            console.error(error);
        }
        const errorMessage = error?.error?.description || error.message || 'An unknown error occurred.';
        return new NextResponse(
            JSON.stringify({ error: `Failed to create Razorpay Payment Link: ${errorMessage}` }),
            { status: 500, headers: { 'Content-Type': 'application/json' } }
        );
    }
}
